### ISSUE TITLE
Editor doesn't load a class

### ISSUE THREAD

**Issue by detouched** [cheptsov/AdvancedExpressionFolding#16] opened 2017-01-11 07:54 UTC
One specific class in a project doesn't open in the Editor: it keeps spinning with "Loading" message but never shows the source. Same class also doesn't show up even if it comes from a maven dependency (in another project).

There're no suspicious messages in the log, and no error/exceptions are shown in IDE UI.

Disabling the Advanced Java Plugin in IDEA settings fixes the problem, so I suppose there's a bug :)

![Uploading Editor Loading Forever](https://media.giphy.com/media/d3YQXqD0sPsqh5eM/giphy.gif)

The affected class is [`com.predic8.membrane.core.RuleManager`](https://github.com/membrane/service-proxy/blob/master/core/src/main/java/com/predic8/membrane/core/RuleManager.java) in the following project: https://github.com/membrane/service-proxy.

**Comment by detouched** [comment] 2017-01-12 01:08
Looks like the same problem happens with `java.util.Collections` class.

**Comment by steveash** [comment] 2017-01-14 19:23
I had this same problem with java.util.Collections and grabbing a thread dump after it happens doesn't show any threads doing anything.  So whatever caused the editor to not be rendered isn't due to any infinite loops or anything.  I also tried adding an extra catch in `buildFoldRegions` (the main entrypoint to the plugin as far as i can tell) to see if any other exceptions were being throw when this issue happened -- but nothing is being thrown. Just stepping through the debugger a few times doesn't show anything about the execution of `buildFoldRegions` to be weird.  I tried setting the IDEA log4j settings to DEBUG to see if anything popped out there -- but nothing.  I'm not a plugin developer so I don't know the next thing to try to narrow down whats going on -- but its easy to reproduce -- just try to open `java.util.Collections`.  It just sits there and spins with no error logged out.

**Comment by zhenxing-cheng** [comment] 2017-01-16 08:47
If one class contains the expressions like null != A, the class in a project doesn't open in the Editor.

The Exception is below:

2017-01-16 16:36:43,370 [ 190090]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2016.3.2  Build #IU-163.10154.41 
2017-01-16 16:36:43,370 [ 190090]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_102 
2017-01-16 16:36:43,370 [ 190090]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-01-16 16:36:43,370 [ 190090]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
2017-01-16 16:36:43,370 [ 190090]  ERROR - aemon.impl.PassExecutorService - OS: Windows 10 
2017-01-16 16:36:43,371 [ 190091]  ERROR - aemon.impl.PassExecutorService - Last Action: EditorBackSpace 
2017-01-16 16:36:44,905 [ 191625]  ERROR - aemon.impl.PassExecutorService - (1043,1043), text: null != A, language = Language: JAVA 
java.lang.AssertionError: (1043,1043), text: null != A, language = Language: JAVA
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:106)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:87)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:72)
	at com.intellij.advancedExpressionFolding.NotNullExpression$1.<init>(NotNullExpression.java:38)
	at com.intellij.advancedExpressionFolding.NotNullExpression.buildFoldRegions(NotNullExpression.java:37)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:162)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)

**Comment by steveash** [comment] 2017-01-19 20:58
I'll see if i cant replicate that and submit a PR for it

**Comment by steveash** [comment] 2017-02-06 14:46
I tested this on 0.4.1 and Collections opens up now so I would consider closing this

**Comment by cheptsov** [comment] 2017-02-27 08:12
@steveash I will close this issue for now. Feel free to re-open if you see it again.

**Closed by cheptsov** 2017-02-27 08:12 UTC
