### ISSUE TITLE
It seems broken on IDEA 2019.3 EAP built on October 9, 2019

### ISSUE THREAD

**Issue by m-titov** [cheptsov/AdvancedExpressionFolding#135] opened 2019-10-09 19:30 UTC
IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.4386.10, built on October 9, 2019
IntelliJ IDEA EAP User

```java        
var gg = "gg";
        
ImmutableSet.of("a", "b", "c").stream()
     .filter(c -> c.getBytes() == gg.getBytes())
     .findFirst()
     .orElseThrow(() -> new IllegalArgumentException("Error " + 10 + " . Incorrect value"));
```
Result with enabled Getters and Setters folding
![image](https://user-images.githubusercontent.com/25036750/66513682-59b52e80-eae4-11e9-8a27-0ae4cdac5971.png)

**Comment by schrek1** [comment] 2019-11-14 13:14
It looks like won't be fixed :/

**Comment by m-titov** [comment] 2019-11-15 09:44
why? It's unreadable. :'(

**Comment by schrek1** [comment] 2019-11-15 10:37
This repo looks that it isn't maintained already by author . I saw that some people asked IntelliJ team for fix, but they don't want to resolve it becouse it is private project outside IntelliJ. It is sad because it is amazing plugin.

**Comment by schrek1** [comment] 2019-11-22 10:50
https://twitter.com/andrey_cheptsov/status/1197823950883045376

**Comment by cheptsov** [comment] 2019-11-22 13:52
Hello folks. The issue is fixed now.
I'm very sorry to provide the fix so late. The thing is the plugin was done by me in my free time which I don't seem to have a lot recently. In case somebody else would like to help with the plugin, please let me know.

**Closed by cheptsov** 2019-11-22 13:52 UTC

**Comment by ciscorucinski** [comment] 2019-11-22 19:32
I would love to try to fork it and do some of my own, but wrapping my head around the current codebase takes a lot. Is there some way to have a write up that summarizes how to work with and around your code. How to think about folding and such?
