### ISSUE TITLE
Folding StringBuilder

### ISSUE THREAD

**Issue by aristotll** [cheptsov/AdvancedExpressionFolding#89] opened 2017-08-02 06:57 UTC
Something like 
```
 StringBuilder sb = new StringBuilder();
 sb.append(" where  t2.service_type=" + PayChnlInfo.SERVICE_TYPE_QUICK);

```
<img width="635" alt="2017-08-02 14 55 53" src="https://user-images.githubusercontent.com/13341544/28861282-bc961ee6-7792-11e7-9189-e1cd54952824.png">

The right part  `}"` is omitted.

A feature or bug? 

Thanks.

**Comment by petteyg** [comment] 2017-08-21 16:15
Looks like duplicate of issue 70, missing the ending `}"`

**Comment by cheptsov** [comment] 2017-11-11 07:20
Should work now with 0.9.9.4.

**Closed by cheptsov** 2017-11-11 07:20 UTC
